#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'

apt-get -y update
apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www
sudo chown -R "$USER:$USER" /usr/share
ufw allow 'Nginx HTTP'
sudo echo 'Welcome to Tediyang tech' > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-enabled/default
service nginx start
